version: '3.8'
services:
  db:
    image: postgres
    container_name: pickify_db
    network_mode: host
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/$USER/docker_pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    network_mode: host
    environment:
      DEFAULT_USER: admin
      DEFAULT_PASS: admin
      RABBITMQ_URL: amqp://admin:admin@localhost:5672
