@postId = 4f9ad19a-0416-4ec0-8149-387acf5f8727
@groupId = 6ffb799f-a017-483c-b364-dd10a6e95252
@optionId = ec8d4b30-ad98-44fc-a51d-d57b28ec4a2b
@userId = 937029d1-995d-4da1-aba2-a90330570c75

@token = token

###

// POST /api/posts

POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "type": "text_poll",
    "is_hidden": false,
    "media_count": 0
}

###

POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{   
    "caption": "post 2 caption",
    "type": "image_poll",
    "is_hidden": true,
    "media_count": 0
}

###

POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{   
    "caption": "post caption",
    "type": "text_poll",
    "media_count": 0
}

###

POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{   
    "caption": "post caption",
    "type": "text_poll",
    "is_hidden": true,
    "media_count": 0
}

##################
// POST /api/posts/:postid/groups
POST http://localhost:3000/api/posts/{{postId}}/groups HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{   
    "groups": [
        {
            "name": "group 1 name",
            "options": [
                {
                    "body": "option 1 body1"
                },
                {
                    "body": "option 1 body2"
                },
                {
                    "body": "option 1 body1"
                },
                {
                    "body": "option 1 body2"
                },
            ]
        }
    ]
}

###

POST http://localhost:3000/api/posts/{{postId}}/groups HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{   
    "groups": [
        {
            "options": [
                {
                    "body":"option 1 body"
                }
            ]
        }
    ]
}

###

POST http://localhost:3000/api/posts/{{postId}}/groups HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{   
    "groups": [
        {
            "name": "group1",
            "options": [
                {
                    "body":"g1o1"
                },
                {
                    "body":"g1o2"
                },
                {
                    "body":"g1o3"
                }
            ]
        },
        {
            "name": "group3",
            "options": [
                {
                    "body":"g3o1"
                },
                {
                    "body":"g3o2"
                },
                {
                    "body":"g3o3"
                }
            ]
        }
    ]
}

##################
// PATCH /api/posts/:postid
PATCH http://localhost:3000/api/posts/{{postId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "finished": true
}
###
// DELETE /api/posts/:postid
DELETE http://localhost:3000/api/posts/{{postId}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}


##################
// PATCH /api/posts/:postid
PATCH  http://localhost:3000/api/posts/{{postId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "finished": true
}

##################
// GET /api/posts
GET http://localhost:3000/api/posts?limit=10&offset=0
Authorization: Bearer {{token}}

##################
// GET /api/posts/:postid
GET http://localhost:3000/api/posts/{{postId}}
Authorization: Bearer {{token}}

##################
// PUT /api/votes/:optionid
PUT http://localhost:3000/api/votes/{{optionId}} HTTP/1.1
Authorization: Bearer {{token}}

##################
// GET /api/users/:userid/posts
GET http://localhost:3000/api/users/{{userId}}/posts?limit=10&0ffset=0
Authorization: Bearer {{token}}

###
POST  http://localhost:3000/api/users/register
Authorization: Bearer {{token}}