// POST /api/posts
//////////////////
POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json

{
    "type": "text_poll",
    "is_hidden": false
}

###

POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json

{   
    "caption": "post caption",
    "type": "text_poll",
    "is_hidden": true
}

###

POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json

{   
    "caption": "post caption",
    "type": "text_poll",
}

###

POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json

{   
    "caption": "post caption",
    "type": "text_poll",
    "is_hidden": "false"
}

##################
// POST /api/posts/:postid/groups
POST http://localhost:3000/api/posts/ba858c96-ddeb-4523-8f10-71030d88807f/groups HTTP/1.1
content-type: application/json

{   
    "groups": [
        {
            "name": "group 1 name",
            "options": [
                {
                    "body":"option 1 body"
                }
            ]
        }
    ]
}

###

POST http://localhost:3000/api/posts/ba858c96-ddeb-4523-8f10-71030d88807f/groups HTTP/1.1
content-type: application/json

{   
    "groups": [
        {
            "options": [
                {
                    "body":"option 1 body"
                }
            ]
        }
    ]
}

###

POST http://localhost:3000/api/posts/ba858c96-ddeb-4523-8f10-71030d88807f/groups HTTP/1.1
content-type: application/json

{   
    "groups": [
        {
            "name": "group name",
            "options": [
                {
                    "body":"option 1 body"
                },
                {
                    "body":"option 2 body"
                },
                {
                    "body":"option 3 body"
                }
            ]
        }
    ]
}

##################
// DELETE /api/posts/:postid
DELETE http://localhost:3000/api/posts/219e9e3d-f209-4f64-b816-6bba8e0d2e43 HTTP/1.1
content-type: application/json


##################
// PATCH /api/posts/:postid


##################
// GET /api/posts


##################
// GET /api/posts/:postid


##################
// PUT /api/votes/:optionid

PUT http://localhost:3000/api/votes/a502658a-d92f-4759-a0fc-8fd79e656172 HTTP/1.1