apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-{{{M3_ENVIRONMENT}}}'
  namespace: {{{M3_NAMESPACE}}}
  labels:
    application: '{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-{{{M3_ENVIRONMENT}}}'
spec:
  replicas: {{{M3_REPLICAS}}}
  selector:
    matchLabels:
      app: {{{M3_COMPONENT}}}
  template:
    metadata:
      labels:
        app: {{{M3_COMPONENT}}}
    spec:
      containers:
        - name: "{{{M3_COMPONENT}}}-main-container"
          image: "{{{M3_IMAGE}}}:{{{M3_VERSION}}}"
          env:
            # Database variables
            - name: APP_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{{M3_APP_USER}}}.{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-db.credentials.postgresql.acid.zalan.do"
                  key: username
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{{M3_APP_USER}}}.{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-db.credentials.postgresql.acid.zalan.do"
                  key: password
            - name: APP_DB_HOST
              value: "{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-db.{{{M3_NAMESPACE}}}.svc.cluster.local"
            # rabbitMQ variables
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: "rabbitmq-dev-default-user"
                  key: password
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "rabbitmq-dev-default-user"
                  key: username
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: "rabbitmq-dev-default-user"
                  key: host
            - name: MEDIA_QUEUE
              value: {{{M3_MEDIA_QUEUE}}}    
            - name: BROKER_QUEUE_PATTERN
              value: {{{M3_BROKER_QUEUE_PATTERN}}}
            # general variables
            - name: NODE_ENV
              value: {{{M3_NODE_ENV}}}
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: pickify-firebase-service-account
              mountPath: /firebase_service_account.json
              subPath: firebase_service_account.json
              readOnly: true
      volumes:  
        - name: pickify-firebase-service-account
          configMap:
            name: '{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-{{{M3_ENVIRONMENT}}}'
