apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{{M3_COMPONENT}}}-deployment"
  namespace: {{{M3_NAMESPACE}}}
  labels:
    app: "{{{M3_COMPONENT}}}-deployment"
spec:
  replicas: {{{M3_REPLICAS}}}
  selector:
    matchLabels:
      app: {{{M3_COMPONENT}}}
  template:
    metadata:
      labels:
        app: {{{M3_COMPONENT}}}
    spec:
      containers:
        - name: "{{{M3_COMPONENT}}}-main-container"
          image: "{{{M3_IMAGE}}}:{{{M3_VERSION}}}"
          env:
            - name: APP_DB_USERNAME
              valueFrom:
              secretKeyRef:
                name: "{{{M3_APP_USER}}}.{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-db.credentials.postgresql.acid.zalan.do"
                key: username
            - name: APP_DB_PASSWORD
              valueFrom:
              secretKeyRef:
                name: "{{{M3_APP_USER}}}.{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-db.credentials.postgresql.acid.zalan.do"
                key: username
            - name: APP_DB_HOST
              value: "{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-db.{{{M3_NAMESPACE}}}.svc.cluster.local"

            - name: DB_URL
              value: {{{M3_POSTS_DB_URL}}}
            - name: NODE_ENV
              value: {{{M3_NODE_ENV}}}
            - name: RABBITMQ_URL
              value: {{{M3_RABBITMQ_URL}}}
            - name: MEDIA_QUEUE
              value: {{{M3_MEDIA_QUEUE}}}              
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP

