apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-{{{M3_ENVIRONMENT}}}-db'
  # pickify.pickify-posts-db.credentials.postgresql.acid.zalan.do
  # M3_APP_USER
  namespace: '{{{M3_NAMESPACE}}}'
  labels:
    application: "{{{M3_PROJECT}}}"
    component: "{{{M3_COMPONENT}}}"
    environment: "{{{M3_ENVIRONMENT}}}"
spec:
  teamId: "{{{M3_PROJECT}}}"
  volume:
    size: '{{{M3_DB_STORAGE}}}'
    storageClass: hcloud-volumes
  resources:
    requests:
      cpu: '{{{M3_DB_CPU}}}'
      memory: '{{{M3_DB_MEMORY}}}'
    limits:
      cpu: '{{{M3_DB_CPU_LIMIT}}}'
      memory: '{{{M3_DB_MEMORY_LIMIT}}}'  
  numberOfInstances: {{{M3_DB_INSTANCES}}}
  users:
    {{{M3_APP_USER}}}:  # database owner
    - superuser
    - createdb
  databases:
    posts: "{{{M3_APP_USER}}}"  # dbname: owner
  postgresql:
    version: "13"
  tolerations:
    - key: db
      value: dev
      operator: "Equal"
      effect: NoSchedule
  nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
       - matchExpressions:
           - key: db
             operator: In
             values:
               - dev
