apiVersion: v1
kind: Service
metadata:
  name: "{{{M3_PROJECT}}}-{{{M3_COMPONENT}}}-{{{M3_ENVIRONMENT}}}"
  namespace: "{{{M3_NAMESPACE}}}"
spec:
  selector:
    application: "{{{M3_PROJECT}}}"
    component: "{{{M3_COMPONENT}}}"
    environment: "{{{M3_ENVIRONMENT}}}"
  ports:
    - port: {{{M3_PORT_BACKEND}}}
      targetPort: {{{M3_MAIN_APP_PORT}}}